"""
RTK/nRTK Gene Database for TNBC Analysis
Contains curated kinase information, pathway membership, and known inhibitors.
"""

KINASE_DATABASE = {
    # ─── Receptor Tyrosine Kinases (RTKs) ───────────────────────────────────
    "EGFR": {
        "full_name": "Epidermal Growth Factor Receptor",
        "type": "RTK",
        "family": "ErbB",
        "chromosome": "7p11.2",
        "tnbc_relevance": "high",
        "overexpression_freq_tnbc": 0.54,
        "pathways": ["MAPK/ERK", "PI3K/AKT", "JAK/STAT"],
        "known_inhibitors": [
            {"drug": "Erlotinib", "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Gefitinib", "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Afatinib",  "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Cetuximab", "type": "monoclonal_antibody", "fda_approved": True, "trial_phase": "approved"},
        ],
        "resistance_mechanisms": ["MET amplification", "KRAS mutation", "ERBB2 amplification"],
        "redundant_pathways": ["FGFR", "MET", "IGFR1"],
        "clinical_notes": "Overexpressed in ~54% TNBC; monotherapy response limited due to pathway redundancy.",
    },
    "ERBB2": {
        "full_name": "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)",
        "type": "RTK",
        "family": "ErbB",
        "chromosome": "17q12",
        "tnbc_relevance": "moderate",
        "overexpression_freq_tnbc": 0.12,
        "pathways": ["MAPK/ERK", "PI3K/AKT"],
        "known_inhibitors": [
            {"drug": "Trastuzumab", "type": "monoclonal_antibody", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Lapatinib",   "type": "small_molecule",      "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Neratinib",   "type": "small_molecule",      "fda_approved": True, "trial_phase": "approved"},
        ],
        "resistance_mechanisms": ["PIK3CA mutation", "PTEN loss", "receptor crosstalk"],
        "redundant_pathways": ["EGFR", "FGFR"],
        "clinical_notes": "Low prevalence in TNBC by definition; co-amplification with EGFR can restore signaling.",
    },
    "FGFR1": {
        "full_name": "Fibroblast Growth Factor Receptor 1",
        "type": "RTK",
        "family": "FGFR",
        "chromosome": "8p11.23",
        "tnbc_relevance": "high",
        "overexpression_freq_tnbc": 0.31,
        "pathways": ["MAPK/ERK", "PI3K/AKT", "STAT"],
        "known_inhibitors": [
            {"drug": "Erdafitinib", "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Pemigatinib", "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "AZD4547",     "type": "small_molecule", "fda_approved": False, "trial_phase": "Phase II"},
        ],
        "resistance_mechanisms": ["FGF/FGFR bypass", "EGFR activation", "RAS mutation"],
        "redundant_pathways": ["EGFR", "FGFR2", "FGFR3"],
        "clinical_notes": "Amplified in mesenchymal TNBC subtype; bypass via EGFR limits single-agent efficacy.",
    },
    "FGFR2": {
        "full_name": "Fibroblast Growth Factor Receptor 2",
        "type": "RTK",
        "family": "FGFR",
        "chromosome": "10q26.13",
        "tnbc_relevance": "moderate",
        "overexpression_freq_tnbc": 0.18,
        "pathways": ["MAPK/ERK", "PI3K/AKT"],
        "known_inhibitors": [
            {"drug": "Erdafitinib", "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Infigratinib","type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "BGJ398",      "type": "small_molecule", "fda_approved": False, "trial_phase": "Phase II"},
        ],
        "resistance_mechanisms": ["FGFR1 bypass", "RAS mutation"],
        "redundant_pathways": ["FGFR1", "FGFR3", "EGFR"],
        "clinical_notes": "Point mutations and fusions detected in TNBC; cross-activation with FGFR1/3 common.",
    },
    "FGFR3": {
        "full_name": "Fibroblast Growth Factor Receptor 3",
        "type": "RTK",
        "family": "FGFR",
        "chromosome": "4p16.3",
        "tnbc_relevance": "moderate",
        "overexpression_freq_tnbc": 0.15,
        "pathways": ["MAPK/ERK", "PI3K/AKT"],
        "known_inhibitors": [
            {"drug": "Erdafitinib", "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Rogaratinib", "type": "small_molecule", "fda_approved": False, "trial_phase": "Phase II"},
        ],
        "resistance_mechanisms": ["FGFR2 bypass", "PIK3CA mutation"],
        "redundant_pathways": ["FGFR1", "FGFR2"],
        "clinical_notes": "Activating mutations found in luminal and TNBC subtypes; family-level inhibition preferred.",
    },
    "MET": {
        "full_name": "MET Proto-Oncogene, Receptor Tyrosine Kinase",
        "type": "RTK",
        "family": "MET",
        "chromosome": "7q31.2",
        "tnbc_relevance": "high",
        "overexpression_freq_tnbc": 0.42,
        "pathways": ["MAPK/ERK", "PI3K/AKT", "Wnt/β-catenin"],
        "known_inhibitors": [
            {"drug": "Crizotinib",    "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Cabozantinib",  "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Capmatinib",    "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Tepotinib",     "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
        ],
        "resistance_mechanisms": ["EGFR activation", "HGF overexpression", "KRAS mutation"],
        "redundant_pathways": ["EGFR", "FGFR", "RON"],
        "clinical_notes": "MET overexpression in ~42% TNBC; key bypass receptor when EGFR is inhibited.",
    },
    "ALK": {
        "full_name": "Anaplastic Lymphoma Kinase",
        "type": "RTK",
        "family": "ALK/LTK",
        "chromosome": "2p23.2",
        "tnbc_relevance": "low",
        "overexpression_freq_tnbc": 0.08,
        "pathways": ["MAPK/ERK", "PI3K/AKT", "JAK/STAT"],
        "known_inhibitors": [
            {"drug": "Crizotinib",  "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Alectinib",   "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Lorlatinib",  "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
        ],
        "resistance_mechanisms": ["ALK secondary mutations", "EGFR activation"],
        "redundant_pathways": ["EGFR", "MET"],
        "clinical_notes": "Rare in breast cancer; ALK fusions occasionally detected in TNBC.",
    },
    # ─── Non-Receptor Tyrosine Kinases (nRTKs) ──────────────────────────────
    "SRC": {
        "full_name": "SRC Proto-Oncogene, Non-Receptor Tyrosine Kinase",
        "type": "nRTK",
        "family": "SRC",
        "chromosome": "20q11.23",
        "tnbc_relevance": "high",
        "overexpression_freq_tnbc": 0.47,
        "pathways": ["MAPK/ERK", "PI3K/AKT", "FAK/integrin"],
        "known_inhibitors": [
            {"drug": "Dasatinib",  "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Bosutinib",  "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Saracatinib","type": "small_molecule", "fda_approved": False, "trial_phase": "Phase II"},
        ],
        "resistance_mechanisms": ["ABL1 activation", "BCR-ABL", "downstream RAS mutation"],
        "redundant_pathways": ["ABL1", "FAK", "YES1"],
        "clinical_notes": "Activated in invasive TNBC; promotes metastasis and therapy resistance.",
    },
    "ABL1": {
        "full_name": "ABL Proto-Oncogene 1, Non-Receptor Tyrosine Kinase",
        "type": "nRTK",
        "family": "ABL",
        "chromosome": "9q34.12",
        "tnbc_relevance": "moderate",
        "overexpression_freq_tnbc": 0.22,
        "pathways": ["MAPK/ERK", "Wnt/β-catenin", "DNA damage response"],
        "known_inhibitors": [
            {"drug": "Imatinib",   "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Dasatinib",  "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
            {"drug": "Nilotinib",  "type": "small_molecule", "fda_approved": True, "trial_phase": "approved"},
        ],
        "resistance_mechanisms": ["BCR-ABL mutations", "SRC activation"],
        "redundant_pathways": ["SRC", "MAPK"],
        "clinical_notes": "Implicated in TNBC invasion and stemness; crosstalk with SRC is well documented.",
    },
    "JAK1": {
        "full_name": "Janus Kinase 1",
        "type": "nRTK",
        "family": "JAK",
        "chromosome": "1p31.3",
        "tnbc_relevance": "moderate",
        "overexpression_freq_tnbc": 0.25,
        "pathways": ["JAK/STAT"],
        "known_inhibitors": [
            {"drug": "Ruxolitinib",  "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Baricitinib",  "type": "small_molecule", "fda_approved": True,  "trial_phase": "approved"},
            {"drug": "Itacitinib",   "type": "small_molecule", "fda_approved": False, "trial_phase": "Phase II"},
        ],
        "resistance_mechanisms": ["STAT3 bypass", "alternative cytokine signaling"],
        "redundant_pathways": ["JAK2", "TYK2", "STAT3"],
        "clinical_notes": "JAK/STAT pathway activated in immune-modulatory TNBC subtype.",
    },
}

# Pathway-level redundancy map: if pathway X is blocked, these can compensate
PATHWAY_REDUNDANCY_MAP = {
    "MAPK/ERK":         ["PI3K/AKT", "JAK/STAT", "Wnt/β-catenin"],
    "PI3K/AKT":         ["MAPK/ERK", "JAK/STAT", "mTOR"],
    "JAK/STAT":         ["MAPK/ERK", "PI3K/AKT"],
    "Wnt/β-catenin":    ["MAPK/ERK", "PI3K/AKT"],
    "FAK/integrin":     ["SRC", "PI3K/AKT"],
    "DNA damage response": ["PI3K/AKT", "MAPK/ERK"],
}

# Variant effect severity scoring
EFFECT_SEVERITY = {
    "stop_gained":          1.0,
    "frameshift_variant":   0.95,
    "splice_acceptor_variant": 0.90,
    "splice_donor_variant": 0.90,
    "start_lost":           0.85,
    "missense_variant":     0.70,
    "inframe_deletion":     0.65,
    "inframe_insertion":    0.60,
    "synonymous_variant":   0.10,
    "intron_variant":       0.05,
    "upstream_gene_variant":0.02,
}
